import { useEffect, useState } from "react";
import { marked } from "marked";
import { api } from "../api/client";
import type { Briefing } from "../api/types";

export default function BriefingPanel() {
  const [briefing, setBriefing] = useState<Briefing | null>(null);
  const [err, setErr] = useState(false);

  useEffect(() => {
    api.briefing().then(setBriefing).catch(() => setErr(true));
  }, []);

  function download() {
    if (!briefing) return;
    const blob = new Blob([briefing.body], { type: "text/markdown" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `pathogenradar-briefing-${briefing.date}.md`;
    a.click();
    URL.revokeObjectURL(url);
  }

  return (
    <div className="panel">
      <div className="section-title">
        <h3 style={{ margin: 0 }}>Minister Briefing</h3>
        <div style={{ display: "flex", gap: 8, alignItems: "center" }}>
          {briefing && (
            <span className="chip" title="Generated by">
              {briefing.provider}
            </span>
          )}
          <button className="btn secondary" onClick={download} disabled={!briefing}>
            Download
          </button>
        </div>
      </div>
      {err && <div className="muted">Unable to load briefing.</div>}
      {briefing ? (
        <div
          className="markdown"
          dangerouslySetInnerHTML={{ __html: marked.parse(briefing.body) as string }}
        />
      ) : (
        !err && <div className="muted">Generating briefing…</div>
      )}
    </div>
  );
}
